---
galaxy_info:
  author: jamesread
  description: Install a k8s node (could be a control/worker).
  license: GPL-3.0-or-later
  min_ansible_version: '2.7'
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - kubernetes
